### ISSUE TITLE
Graphic issue on rotate

### ISSUE THREAD

**Issue by MP85** [edekhayser/FrostedSidebar#10]
When sidebar is open if you rotate the device to landscape and then portrait again, sidebar appear with graphic bug.

Expected:
![schermata 2015-04-10 alle 09 29 26](https://cloud.githubusercontent.com/assets/4517106/7083594/27f874f0-df64-11e4-8a84-931f04786d54.png)

Bug:
![schermata 2015-04-10 alle 09 29 11](https://cloud.githubusercontent.com/assets/4517106/7083601/3b82b9b8-df64-11e4-9cbd-8b90ec34e0c5.png)

**Comment by edekhayser** [comment]
In the sample project, the TabBarController automatically dismisses on
rotation to avoid issues like this. If you need, I can look into this in
the next week or so.

**Comment by edekhayser** [comment]
Actually, this bug is not from my project; this comes form
RNFrostedSidebar.

**Comment by MP85** [comment]
Ok, thank you.
