### ISSUE TITLE
Loading programmatically the tab > 3

### ISSUE THREAD

**Issue by phemka** [edekhayser/FrostedSidebar#11]
Great job ! I will use in my future app.

func sidebar(sidebar: FrostedSidebar, didTapItemAtIndex index: Int)
work for index > 3
but self.selectedIndex work only for index 0...3

How to load the next tab (4, 5, 6) programmatically when the app is loaded ?

**Comment by edekhayser** [comment]
Sorry I have not gotten back to you sooner, I have been quite busy. I'm not sure what your issue is; can you please give me a better idea of what you are trying to accomplish?

**Comment by phemka** [comment]
No problem, thanks for your support 😉.
I need to open the app with the last viewcontroller used.
I keep the tabbar index when the app quit and retrieve the saved tabbar index with NSUserDefaults.

In the tabbarController, I use this method : 
        let defaults = NSUserDefaults.standardUserDefaults()
        if let tabName = defaults.stringForKey("tabKey") {
            switch tabName {
            case 0:
                self.selectedIndex = 0
          .....

This work perfectly for the index 0 to 3, but doesn't for the next tab. I think because it's the tab for the "moretableview".

The question is : How to have the same behavior "tapping" the sidebar or "opening the app" to have the chosen viewController.

Hope is clearer.

**Comment by edekhayser** [comment]
In your Tab Bar Controller, do you have the following line?

moreNavigationController.navigationBar.hidden = true

I believe that is how I fixed this issue in the sample project.

**Comment by phemka** [comment]
Yes, I have. The TabBarController is like yours.
But :
self.selectedIndex = 0  -> open viewController 0
self.selectedIndex = 1  -> open viewController 1
self.selectedIndex = 2  -> open viewController 2
self.selectedIndex = 3  -> open viewController 3
Logical !
self.selectedIndex = 4  -> open viewController 0
Stange !?

**Comment by edekhayser** [comment]
Okay, so here is a temporary fix, which I may end up making a permanent change as a result of:

In FrostedSidebar.swift, change `private didTapItemAtIndex(index: Int)` to `public didTapItemAtIndex(index: Int)`

Now, go to your Tab Bar Controller and change the line `self.selectedIndex = 4` to `sideBar.didTapItemAtIndex(4)`

Let me know how this works for you.

**Comment by phemka** [comment]
Great !
It works. Thanks.
