### ISSUE TITLE
Won't init at runtime. Installation issue?

### ISSUE THREAD

**Issue by jimijon** [edekhayser/FrostedSidebar#12]
I am trying this out on a little project that I have. I added the TabBarController.swift and the FrostedSidebar.swift files to my app. In story board I added a TabBarController and made TabBarController.swift its object. Then I made this the startup view.

I run the app, but it never actually calls the FrostedSideBar init in TabBarController.

sidebar = FrostedSidebar(itemImages: [
			UIImage(named: "gear")!,
			UIImage(named: "globe")!,
			UIImage(named: "profile")!,
			UIImage(named: "profile")!,
			UIImage(named: "profile")!,
			UIImage(named: "profile")!,
			UIImage(named: "star")!],
			colors: [
				UIColor(red: 240/255, green: 159/255, blue: 254/255, alpha: 1),
				UIColor(red: 255/255, green: 137/255, blue: 167/255, alpha: 1),
				UIColor(red: 126/255, green: 242/255, blue: 195/255, alpha: 1),
				UIColor(red: 126/255, green: 242/255, blue: 195/255, alpha: 1),
				UIColor(red: 126/255, green: 242/255, blue: 195/255, alpha: 1),
				UIColor(red: 126/255, green: 242/255, blue: 195/255, alpha: 1),
				UIColor(red: 119/255, green: 152/255, blue: 255/255, alpha: 1)],
			selectedItemIndices: NSIndexSet(index: 0))

It seems to skip over the initializer. 

Did I install it wrong?

**Comment by edekhayser** [comment]
Your code appears to be correct, so I can't say what is wrong in your project. Try comparing it to the sample project, and if you still can't find anything wrong, then post some more information/code so I can try to help you better.
