### ISSUE TITLE
Cocoapods

### ISSUE THREAD

**Issue by ivangodfather** [edekhayser/FrostedSidebar#14]
Love it so muchs! Will be available through cocoapods? Thank you!

**Comment by edekhayser** [comment]
@ivangodfather I haven't gotten around to Cocoapods yet, but if you'd like to submit a pull request, it's always welcome :)

Otherwise, I'll try to get around to it one of these days.

**Comment by lfarah** [comment]
I done this implementation myself last month for my library. Just follow [this post](https://guides.cocoapods.org/making/making-a-cocoapod.html) and [this checklist](https://github.com/thellimist/EZPods).

**Comment by lfarah** [comment]
@edekhayser We can't just submit a pull request because you as the owner have to send it to CocoaPods

**Comment by edekhayser** [comment]
@lfarah Thanks for the links, I just set it up. If you could verify that it is working, it would be much appreciated.
