### ISSUE TITLE
Can't get buttons to work

### ISSUE THREAD

**Issue by Brain2success** [edekhayser/FrostedSidebar#16]
What a fantastic sidebar menu!

I added the swift file in my project;
I added the script: 
var frostedSidebar: FrostedSidebar = FrostedSidebar(images: imageArray, colors: colorArray, selectionStyle: chosenSelectionStyle)
And changed the right things;

I added the following script to a button function:
frostedSidebar.showInViewController( self, animated: true )

And al of this works perfect! The sidebar is showing and the animations works fine. 

But i just can get the button action inside the sidebar to work. I don't have a tabbar in my project. I do have 3 viewcontrollers and added a navigation controller. I know how to use segues. 

Can you tell me how to get respons from the sidebar buttons? I don't know how and where to use the given script: frostedSidebar.actionForIndex[idx] = { /* actions */ }

**Comment by Brain2success** [comment]
Ok, added the tabbar. Now it works fine! Tnx!

**Comment by edekhayser** [comment]
Glad I could help 😜

**Comment by Brain2success** [comment]
Hi evan,

Any idea how to preform a tableView refresh if a user hits a button in the sidebar.

I know how to preform a refresh normally, but I get an error if I call the 'refresh' function in your code.
Errorline: TableView.reloadData()

I think it's the same problem but I would also like to refresh of reload the view if a user hits the button from the current view controller.

Kind regards,

Ronald Baks

_____________________________

**Comment by edekhayser** [comment]
It depends on the error. Try adding "self." so it says "self.tableView.reloadData()"
