### ISSUE TITLE
inside a nabbar / navcontroller.

### ISSUE THREAD

**Issue by mdaymond** [edekhayser/FrostedSidebar#6]
Is there anyway to have the menu appear below the nav bar ?

**Comment by PickMe** [comment]
And how about changing the Position of the first button to avoid overlapping the Buttons with the navbar?
I don't mind about the blurred area.... ;)

**Comment by lilpennyjr** [comment]
Heres what I did in the FrostedSidebar.swift file to move the first button to avoid overlapping with the navbar. It starts at line 371:

 private func layoutItems(){
        let leftPadding: CGFloat = (width - itemSize.width) / 2
        let topPadding: CGFloat = (width - itemSize.height) / 1.7
        for (index, item) in enumerate(itemViews){
            let idx: CGFloat = CGFloat(index)
            let frame = CGRect(x: leftPadding, y: topPadding*(idx + 1) + itemSize.height*idx + topPadding, width:itemSize.width, height: itemSize.height)
            item.frame = frame
            item.layer.cornerRadius = frame.size.width / 2
            item.layer.borderColor = UIColor.clearColor().CGColor
            item.alpha = 0
            if selectedIndices.containsIndex(index){
                if borderColors != nil{
                    item.layer.borderColor = borderColors![index].CGColor
                }
            }
        }
        let itemCount = CGFloat(itemViews.count)
        contentView.contentSize = CGSizeMake(0, itemCount * (itemSize.height + topPadding) + topPadding)
    }

**Comment by edekhayser** [comment]
Check out the latest commit. This feature is now part of the sidebar: set `adjustForNavigationBar = true`
