### ISSUE TITLE
How to add web view?

### ISSUE THREAD

**Issue by ksuchar** [edekhayser/FrostedSidebar#9]
Hi, i would like to add a web view to the view controller 2 so when the user presses the 'globe' icon it takes them to a web page. I added a web view and connected it to ViewController.swift and then loaded a url with url requests. Unfortunately i get an exception error when I run the program... Any ideas??

Thanks so much for this amazing sidebar demo app!!

**Comment by edekhayser** [comment]
What is the exception that you run into? This is probably unrelated to the
sidebar, however. You might get faster/better answers on StackOverflow
